export default {
    AUTH_REGISTER: 'AUTH_REGISTER',
    AUTH_LOGIN   : 'AUTH_LOGIN',
    AUTH_LOGOUT  : 'AUTH_LOGOUT',
    AUTH_LOADING : 'AUTH_LOADING',
    AUTH_SUCCESS : 'AUTH_SUCCESS',
    AUTH_ERROR   : 'AUTH_ERROR',
    AUTH_ME      : 'AUTH_ME',
    USER         : 'USER',
    USER_NULL    : 'USER_NULL',
    USER_ERROR   : 'USER_ERROR',
    USER_LOADING : 'USER_LOADING',
    GET_EVENTS   : 'GET_EVENTS',
    GET_EVENT    : 'GET_EVENT'
}
