export default {
    AUTH_REGISTER: 'AUTH_REGISTER',
    AUTH_LOGIN   : 'AUTH_LOGIN',
    AUTH_LOGOUT  : 'AUTH_LOGOUT',
    AUTH_LOADING : 'AUTH_LOADING',
    AUTH_SUCCESS : 'AUTH_SUCCESS',
    AUTH_ERROR   : 'AUTH_ERROR',
    SET_USER     : 'SET_USER',
    GET_EVENTS   : 'GET_EVENTS',
    GET_EVENT    : 'GET_EVENT'
}
